[package]
name = "todo"
version = "0.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.8", features = ["derive"] }
dirs = "5.0.1"
env_logger = "0.11.3"
home = "0.5.9"
log = "0.4.22"
once_cell = "1.19.0"
rusqlite = "0.31.0"
thiserror = "1.0.62"

[dev-dependencies]
tempfile = "3.10.1"
